apiVersion: v1
kind: ConfigMap
metadata:
  name: github-analytics-config
  namespace: github-analytics
  labels:
    app.kubernetes.io/part-of: github-analytics
data:
  PYTHONUNBUFFERED: "1"
  LOG_LEVEL: "info"
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
